// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBMYSRXUABC-3-l-VDV9ezqxvFL_cHTRI',
    appId: '1:653357952914:web:ff7ab7fb3e3703adb19b4b',
    messagingSenderId: '653357952914',
    projectId: 'barberapp-33582',
    authDomain: 'barberapp-33582.firebaseapp.com',
    storageBucket: 'barberapp-33582.firebasestorage.app',
    measurementId: 'G-JTR0B4P1ES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4A9TUWFBr8Y6YAxk7AVQMb0smaYxCR-4',
    appId: '1:653357952914:android:415a301f30c2d798b19b4b',
    messagingSenderId: '653357952914',
    projectId: 'barberapp-33582',
    storageBucket: 'barberapp-33582.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5MPZRZ90BuuyVMKOAcTS8y7O72Rk28rs',
    appId: '1:653357952914:ios:935dae4270241fe2b19b4b',
    messagingSenderId: '653357952914',
    projectId: 'barberapp-33582',
    storageBucket: 'barberapp-33582.firebasestorage.app',
    iosBundleId: 'com.example.barberApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBMYSRXUABC-3-l-VDV9ezqxvFL_cHTRI',
    appId: '1:653357952914:web:68b45423fb280299b19b4b',
    messagingSenderId: '653357952914',
    projectId: 'barberapp-33582',
    authDomain: 'barberapp-33582.firebaseapp.com',
    storageBucket: 'barberapp-33582.firebasestorage.app',
    measurementId: 'G-GGSCP5GYS4',
  );
}
